# Generated by Django 4.0.8 on 2023-01-25 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
    ]
