# Generated by Django 4.0.8 on 2023-01-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notis', '0004_remove_notification_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
