# Generated by Django 4.1.7 on 2023-04-03 04:46

import authentication.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('objects', authentication.managers.CustomUserManager()),
            ],
        ),
    ]
