# Generated by Django 4.1.7 on 2023-04-04 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_student_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faculty",
            options={"verbose_name": "Office", "verbose_name_plural": "Faculties"},
        ),
    ]
