# Generated by Django 4.1.7 on 2023-04-04 08:42

import authentication.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_faculty_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("location", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Office",
                "verbose_name_plural": "Office",
            },
            bases=("authentication.user",),
            managers=[
                ("objects", authentication.managers.CustomUserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name="faculty",
            options={"verbose_name": "Faculty", "verbose_name_plural": "Faculties"},
        ),
    ]
