# Generated by Django 4.1 on 2023-04-03 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('section', models.CharField(max_length=2, null=True)),
                ('courseTitle', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseTitle', models.CharField(max_length=25)),
                ('courseCode', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=1)),
                ('section', models.CharField(max_length=1)),
                ('faculty', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('usn', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('section', models.CharField(max_length=2)),
            ],
        ),
    ]
