# Generated by Django 4.1.7 on 2023-04-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendence_Management', '0002_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['usn']},
        ),
    ]
