# Generated by Django 4.1 on 2023-04-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendence_Management', '0003_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultycourse',
            name='academicYear',
            field=models.CharField(default=2022, max_length=7),
            preserve_default=False,
        ),
    ]
