# Generated by Django 4.0.8 on 2023-01-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
    ]
