# Generated by Django 4.1.7 on 2023-04-16 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty_dashboard_proctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CGPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USN', models.CharField(max_length=10)),
                ('total_credits_registered', models.DecimalField(decimal_places=0, max_digits=2)),
                ('total_credits_earned', models.DecimalField(blank=True, decimal_places=0, max_digits=2)),
                ('cgpa', models.DecimalField(decimal_places=0, max_digits=1)),
                ('sem', models.DecimalField(decimal_places=0, max_digits=1)),
            ],
            options={
                'ordering': ['USN'],
            },
        ),
        migrations.CreateModel(
            name='Fastrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USN', models.CharField(max_length=10)),
                ('sem', models.IntegerField()),
                ('courseName', models.TextField()),
                ('courseCode', models.TextField()),
                ('credit', models.TextField()),
                ('registration', models.TextField(blank=True, null=True)),
                ('attemptNumber', models.FloatField(blank=True, null=True)),
                ('attendance', models.FloatField(blank=True, null=True)),
                ('CIE', models.FloatField(blank=True, null=True)),
                ('SEE', models.FloatField(blank=True, max_length=1, null=True)),
                ('GradePoints', models.FloatField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FastrackCourseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_subjects', models.IntegerField(max_length=1)),
                ('student_usn', models.CharField(max_length=10)),
                ('sem', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USN', models.CharField(max_length=10)),
                ('sem', models.IntegerField()),
                ('courseName', models.TextField()),
                ('courseCode', models.TextField()),
                ('credit', models.TextField()),
                ('registration', models.TextField()),
                ('attemptNumber', models.FloatField(blank=True, null=True)),
                ('attendance', models.FloatField(blank=True, null=True)),
                ('CIE', models.FloatField(blank=True, null=True)),
                ('SEE', models.FloatField(blank=True, max_length=1, null=True)),
                ('GradePoints', models.CharField(blank=True, max_length=1, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('facultyHandling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='faculty_dashboard_proctor.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USN', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('permanent_address', models.TextField()),
                ('current_address', models.TextField()),
                ('phone_number', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=3)),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('father_occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('father_phone_number', models.CharField(max_length=10)),
                ('mother_phone_number', models.CharField(max_length=10)),
                ('father_email', models.EmailField(max_length=254)),
                ('mother_email', models.EmailField(max_length=254)),
                ('guardian_name', models.CharField(max_length=200)),
                ('guardian_phone_number', models.CharField(max_length=10)),
                ('guardian_email', models.EmailField(max_length=254)),
                ('class_10th_school', models.CharField(max_length=200)),
                ('class_10th_board', models.CharField(max_length=200)),
                ('class_10th_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('class_10th_year', models.DecimalField(decimal_places=0, max_digits=4)),
                ('class_12th_school', models.CharField(max_length=200)),
                ('class_12th_board', models.CharField(max_length=200)),
                ('class_12th_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('class_12th_year', models.DecimalField(decimal_places=0, max_digits=4)),
                ('class_Diploma_school', models.CharField(blank=True, max_length=200, null=True)),
                ('class_Diploma_board', models.CharField(blank=True, max_length=200, null=True)),
                ('class_Diploma_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('class_Diploma_year', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('isApproved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('sem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student_dashboard_proctor.sem')),
            ],
            bases=('student_dashboard_proctor.sem',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USN', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('current_sem', models.IntegerField(blank=True, null=True)),
                ('proctor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='faculty_dashboard_proctor.faculty')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='courseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_subjects', models.IntegerField(max_length=1)),
                ('student_usn', models.CharField(max_length=10)),
                ('sem', models.IntegerField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='faculty_dashboard_proctor.faculty')),
            ],
        ),
    ]
