# Generated by Django 4.1.3 on 2023-04-03 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard_proctor', '0003_alter_student_options_student_usn_student_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
