<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-04-04 07:52
=======
# Generated by Django 4.1 on 2023-04-03 18:28
>>>>>>> main

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("student_dashboard_proctor", "0004_remove_student_user"),
=======
        ('student_dashboard_proctor', '0004_remove_student_user'),
>>>>>>> main
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name="Courses",
            fields=[
                (
                    "sem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="student_dashboard_proctor.sem",
                    ),
                ),
            ],
            bases=("student_dashboard_proctor.sem",),
=======
            name='Courses',
            fields=[
                ('sem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student_dashboard_proctor.sem')),
            ],
            bases=('student_dashboard_proctor.sem',),
>>>>>>> main
        ),
    ]
