# Generated by Django 4.1.7 on 2023-04-04 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("student_dashboard_proctor", "0004_remove_student_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "sem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="student_dashboard_proctor.sem",
                    ),
                ),
            ],
            bases=("student_dashboard_proctor.sem",),
        ),
    ]
