# Generated by Django 4.1.3 on 2023-04-04 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_dashboard_proctor', '0001_initial'),
        ('student_dashboard_proctor', '0005_courses_alter_student_current_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sem',
            name='facultyHandling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='faculty_dashboard_proctor.faculty'),
        ),
    ]
