# Generated by Django 4.1.3 on 2023-04-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard_proctor', '0006_sem_facultyhandling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sem',
            name='is_marks_approved',
        ),
        migrations.AddField(
            model_name='sem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
