# Generated by Django 4.1.3 on 2023-04-04 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_dashboard_proctor', '0001_initial'),
        ('student_dashboard_proctor', '0007_remove_sem_is_marks_approved_sem_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserequest',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='faculty_dashboard_proctor.faculty'),
        ),
    ]
