# Generated by Django 4.1.3 on 2023-04-04 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard_proctor', '0005_courses'),
        ('student_dashboard_proctor', '0008_alter_courserequest_faculty'),
    ]

    operations = [
    ]
