# Generated by Django 4.1.3 on 2023-04-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard_proctor', '0009_merge_0005_courses_0008_alter_courserequest_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sem',
            name='GradePoints',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
