# Generated by Django 4.1.3 on 2023-04-07 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("faculty_dashboard_proctor", "0001_initial"),
        ("student_dashboard_proctor", "0010_alter_sem_gradepoints"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fastrack",
            name="registration",
        ),
        migrations.CreateModel(
            name="FastrackCourseRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no_subjects", models.IntegerField(max_length=1)),
                ("student_usn", models.CharField(max_length=10)),
                ("sem", models.IntegerField()),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="faculty_dashboard_proctor.faculty",
                    ),
                ),
            ],
        ),
    ]
