# Generated by Django 4.1.3 on 2023-04-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "student_dashboard_proctor",
            "0011_remove_fastrack_registration_fastrackcourserequest",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fastrackcourserequest",
            name="faculty",
        ),
        migrations.AddField(
            model_name="fastrack",
            name="numberOfCourses",
            field=models.IntegerField(default=0),
        ),
    ]
