# Generated by Django 4.1.3 on 2023-04-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "student_dashboard_proctor",
            "0013_remove_fastrack_numberofcourses_fastrack_no_subjects",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fastrack",
            name="no_subjects",
        ),
    ]
