# Generated by Django 4.1.3 on 2023-04-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_dashboard_proctor", "0014_remove_fastrack_no_subjects"),
    ]

    operations = [
        migrations.AddField(
            model_name="fastrack",
            name="registration",
            field=models.TextField(blank=True, null=True),
        ),
    ]
