# Generated by Django 4.0.8 on 2023-01-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0007_profile_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
