# Generated by Django 4.0.8 on 2023-01-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0008_alter_profile_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='thread_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
