# Generated by Django 4.0.8 on 2023-01-25 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('threads', '0011_category_thread_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='watched',
            field=models.ManyToManyField(blank=True, default=None, related_name='watched', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WatchThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Watch', 'Watch'), ('Unwatch', 'Unwatch')], default='Watch', max_length=10)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
