# Generated by Django 4.1.7 on 2023-04-17 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '__first__'),
        ('CSE_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomName', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('num_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Assigned_Exam_Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CSE_site.course')),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CSE_site.exam')),
                ('room_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='online_cie_allocator.room')),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.student')),
            ],
            options={
                'ordering': ['stud_id', 'exam_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='assigned_exam_room',
            constraint=models.UniqueConstraint(fields=('stud_id', 'course_id', 'exam_id'), name='unique_stud_id_course_id_exam_id_combination'),
        ),
    ]
