# Generated by Django 4.1.7 on 2023-04-16 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_cie_allocator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assigned_Exam_Room',
        ),
    ]
