# Generated by Django 4.1.7 on 2023-04-16 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_office_alter_faculty_options'),
        ('CSE_site', '0002_alter_course_code_alter_course_title_and_more'),
        ('online_cie_allocator', '0002_delete_assigned_exam_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assigned_Exam_Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CSE_site.course')),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CSE_site.exam')),
                ('room_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='online_cie_allocator.room')),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.student')),
            ],
            options={
                'ordering': ['stud_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='assigned_exam_room',
            constraint=models.UniqueConstraint(fields=('stud_id', 'course_id'), name='unique_stud_id_course_id_combination'),
        ),
    ]
