# Generated by Django 4.1.7 on 2023-04-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_cie_allocator', '0003_assigned_exam_room_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assigned_exam_room',
            options={'ordering': ['stud_id', 'exam_id']},
        ),
        migrations.RemoveConstraint(
            model_name='assigned_exam_room',
            name='unique_stud_id_course_id_combination',
        ),
        migrations.AddConstraint(
            model_name='assigned_exam_room',
            constraint=models.UniqueConstraint(fields=('stud_id', 'course_id', 'exam_id'), name='unique_stud_id_course_id_exam_id_combination'),
        ),
    ]
