# Generated by Django 4.1.7 on 2023-04-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSE_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='course_type',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='exam_type',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
