# Generated by Django 4.0.8 on 2023-01-31 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notis', '0003_notification_reciever2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_seen',
        ),
    ]
